apiVersion: v1
kind: Service
metadata:
  name: goqtt-service
  namespace: default
  labels:
    app: goqtt-broker
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
  selector:
    app: goqtt-broker
  sessionAffinity: None
